name = "DASKR"
uuid = "165a45c3-f624-5814-8e85-3bdf39a7becd"
version = "2.9.1"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DASKR_jll = "655fdf9c-4522-5e7e-b537-e46a52300ea6"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
PrecompileTools = "aea7be01-6a6a-4083-8856-8a6e6704d82a"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Compat = "4.1"
DASKR_jll = "1"
DiffEqBase = "6"
PrecompileTools = "1.2"
Reexport = "1.0"
julia = "1.6"

[extras]
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Pkg", "Test"]
