name = "DASKR"
uuid = "165a45c3-f624-5814-8e85-3bdf39a7becd"
version = "2.7.0"

[deps]
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
DASKR_jll = "655fdf9c-4522-5e7e-b537-e46a52300ea6"
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
Compat = "2, 3"
DiffEqBase = "6"
Reexport = "0.2, 1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
